### ISSUE TITLE
ValueError: Cannot feed value of shape (0,) for Tensor 'Placeholder_1:0', which has shape '(16, 4, 4, 3)'

### ISSUE THREAD

**Issue by airsteffen** [AndrewBeers/DeepZine#1]
Hi, I'm trying to train my own dataset, but have this error. Do you have any ideas?
`Traceback (most recent call last):`
`File "wrapper.py", line 29, in <module>`
`process_config(sys.argv[1])`
`File "wrapper.py", line 22, in process_config`
`gan.execute()`
`File "/floyd/home/deepzine.py", line 89, in execute`
`self.train_gan()`
`File "/floyd/home/deepzine.py", line 204, in train_gan`
`pggan.train()`
`File "/floyd/home/model.py", line 283, in train`
`sess.run(self.opti_D, feed_dict={self.images: real_data, self.latent: sample_latent})`
`File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 887, in run
run_metadata_ptr)`
`File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1086, in _run
str(subfeed_t.get_shape())))`
`ValueError: Cannot feed value of shape (0,) for Tensor 'Placeholder_1:0', which has shape '(16, 4, 4, 3)'`

**Comment by AnnaBeers** [comment]
It looks like data is not being fed into your network, perhaps because something went wrong in the data-loading process, but unfortunately I cannot troubleshoot without understanding more about the dataset you are trying to train on. Are you working with similar data downloaded from the Internet Archive?
